locale                   : "en-US"
site_theme               : "default"
title                    : "James Spyrou's Webpage"
title_separator          : "-"
name                     : &name "James Spyrou"
description              : &description "Neuroscientist"
url                      : https://jamesspyrou.github.io
repository               : "jamesspyrou/jamesspyrou.github.io"
