locale                   : "en-US"
site_theme               : "default"
title                    : "James Spyrou"
name                     : &name "James Spyrou"
description              : &description "The personal webpage of Australian neuroscientist and researcher James Spyrou."
url                      : https://jamesspyrou.github.io/
